CourseMasterApp/CourseMasterApp/urls.py
from django.contrib import admin
from django.urls import include, path
from .import views,user_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base',views.BASE,name='base'),
    path('404',views.PAGE_NOT_FOUND,name='404'),
    path('',views.HOME,name='home'),
    path('courses',views.SINGLE_COURSE,name="single_course"),
    path('courses/filter-data',views.filter_data,name="filter-data"),
    path('course/<slug:slug>',views.COURSE_DETAILS,name='course_details'),
    path('search',views.SEARCH_COURSE,name='search_course'),
    
    path('contact',views.CONTACT_US,name="contact_us"),
    path('about',views.ABOUT_US,name="about_us"),

    path('accounts/register',user_login.REGISTER,name="register"),
    path('accounts/', include('django.contrib.auth.urls')),

    path('doLogin',user_login.DO_LOGIN,name='doLogin'),
    path('accounts/profile',user_login.PROFILE,name='profile'),
    path('accounts/profile/update',user_login.PROFILE_UPDATE,name='profile_update'),

    path('checkout/<slug:slug>',views.CHECKOUT,name='checkout'),

    path('my-course',views.MY_COURSE,name='my_course'),

    path('verify_payment',views.VERIFY_PAYMENT,name='verify_payment'),
    # path('verify_iyzico',views.VERIFY_IYZICO,name='verify_iyzico'),
    path('course/watch-course/<slug:slug>',views.WATCH_COURSE, name='watch_course'),
    path('logout/',user_login.LOGOUT, name='logout'),
    path('our_team',views.OURTEAM,name="our_team"),
    
    
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

CourseMasterApp/app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save

# Create your models here.

class Categories(models.Model):
    icon = models.CharField(max_length=200,null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
    def get_all_category(self):
        return Categories.objects.all().order_by("id")

class Author(models.Model):
    author_profile = models.ImageField(upload_to="Media/author")
    title=models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=100, null=True)
    about_author = models.TextField()
    
    def __str__(self):
        return self.name
    
class OurTeam(models.Model):
    our_team = models.ImageField(upload_to="Media/ourTeam")
    ourTeam_title=models.CharField(max_length=100, null=True)
    ourTeam_name = models.CharField(max_length=100, null=True)
    ourTeamabout = models.TextField()
    
    def __str__(self):
        return self.ourTeam_name
    
    
class Level(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Language(models.Model):
    language=models.CharField(max_length=100)

    def __str__(self):
        return self.language


class Course(models.Model):
    STATUS = (
        ('PUBLISH','PUBLISH'),
        ('DRAFT','DRAFT'),
    )
    
    featured_image = models.ImageField(upload_to="Media/featured_img",null=True)
    featured_video = models.CharField(max_length = 300, null=True)
    title = models.CharField(max_length=500)
    created_at = models.DateField(auto_now_add=True)
    author = models.ForeignKey(Author,on_delete=models.CASCADE,null=True)
    category =models.ForeignKey(Categories,on_delete=models.CASCADE)
    level=models.ForeignKey(Level,on_delete=models.CASCADE,null=True)
    description = models.TextField()
    price = models.IntegerField(null=True,default=0)
    discount = models.IntegerField(null=True)
    language=models.ForeignKey(Language,on_delete=models.CASCADE,null=True)
    Deadline=models.CharField(max_length=100,null=True)
    slug = models.SlugField(default='',max_length=500,null=True,blank=True)
    status=models.CharField(choices=STATUS,max_length=100,null=True)
    Certificate=models.CharField(null=True,max_length=100)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("course_details",kwargs={'slug':self.slug})
    
def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug= new_slug
    qs =Course.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug ="%s-%s" % (slug,qs.first().id)
        return create_slug(instance,new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender,instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
pre_save.connect(pre_save_post_receiver,Course)

class What_you_learn(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    points = models.CharField(max_length=500)
    
    def __str__(self):
        return self.points
    
class Requirements(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    points = models.CharField(max_length=500)
    
    def __str__(self):
        return self.points

class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete = models.CASCADE)
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name + " - " + self.course.title

class Video(models.Model):
    serial_number = models.IntegerField(null=True)
    thumbnail = models.ImageField(upload_to="Media/Yt_Thumbnail", null=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    youtube_id = models.CharField(max_length=200)
    time_duration = models.IntegerField(null=True)
    preview = models.BooleanField(default=False)
    
    def __str__(self):
        return self.title
    
class UserCource(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    paid=models.BooleanField(default=0)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name + " - " + self.course.title
    
class Payment(models.Model):
    order_id=models.CharField(max_length=100,null=True,blank=True)
    payment_id=models.CharField(max_length=100,null=True,blank=True)
    user_course=models.ForeignKey(UserCource,on_delete=models.CASCADE,null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    course=models.ForeignKey(Course,on_delete=models.CASCADE,null=True)
    date=models.DateTimeField(auto_now_add=True)
    status=models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name + " -- " + self.course.title

CourseMasterApp/templates/components/footer.html
{% load static %}

<!-- FOOTER
    ================================================== -->
<footer class="py-8 pt-md-11 position-relative bg-white">
  <div class="position-absolute bottom-0 left-0 shape-flip-both">
    <img
      src="{% static 'assets/img/illustrations/illustration-7.svg' %}"
      class="img-fluid"
      alt="..."
    />
  </div>

  <div class="container container-wd">
    <div class="row" id="accordionFooter">
      <div class="col-12 col-md-4 col-lg-3">
        <!-- Brand -->
        <img
          src="{% static 'assets/img/coursemaster-logo.png' %}"
          alt="Course Master"
          class="footer-brand img-fluid mb-4 h-140p"
        />

        <!-- Text -->
        <p class="text-gray-800 mb-4 font-size-sm-alone">
          Aksoy Mah. Karşıyaka/İzmir Türkiye
        </p>

        <div class="mb-4">
          <a href="tel:1234567890" class="text-gray-800 font-size-sm-alone"
            >123 456 7890</a
          >
        </div>

        <div class="mb-4">
          <a
            href="mailto:info@coursemaster.com.tr"
            class="text-gray-800 font-size-sm-alone"
            >info@coursemaster.com.tr</a
          >
        </div>

        <!-- Social -->
        <ul class="list-unstyled list-inline list-social mb-4 mb-md-0">
          <li class="list-inline-item list-social-item">
            <a
              class="text-secondary font-size-sm w-36 h-36 shadow-dark-hover d-flex align-items-center justify-content-center rounded-circle border-hover"
            >
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="list-inline-item list-social-item">
            <a
              class="text-secondary font-size-sm w-36 h-36 shadow-dark-hover d-flex align-items-center justify-content-center rounded-circle border-hover"
            >
              <i class="fab fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item list-social-item">
            <a
              class="text-secondary font-size-sm w-36 h-36 shadow-dark-hover d-flex align-items-center justify-content-center rounded-circle border-hover"
            >
              <i class="fab fa-instagram"></i>
            </a>
          </li>
          <li class="list-inline-item list-social-item">
            <a
              class="text-secondary font-size-sm w-36 h-36 shadow-dark-hover d-flex align-items-center justify-content-center rounded-circle border-hover"
            >
              <i class="fab fa-linkedin-in"></i>
            </a>
          </li>
        </ul>
      </div>

      <div class="col-12 col-md-4 col-lg-2">
        <div class="mb-5 mb-xl-0 footer-accordion">
          <!-- Heading -->
          <div id="widgetOne">
            <h5 class="mb-5">
              <button
                class="text-dark fw-medium footer-accordion-toggle d-flex align-items-center"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#widgetcollapseOne"
                aria-expanded="true"
                aria-controls="widgetcollapseOne"
              >
                Menü
                <span class="ms-auto text-dark">
                  <!-- Icon -->
                  <svg
                    width="15"
                    height="2"
                    viewBox="0 0 15 2"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <rect width="15" height="2" fill="currentColor" />
                  </svg>

                  <svg
                    width="15"
                    height="16"
                    viewBox="0 0 15 16"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M0 7H15V9H0V7Z" fill="currentColor" />
                    <path
                      d="M6 16L6 8.74228e-08L8 0L8 16H6Z"
                      fill="currentColor"
                    />
                  </svg>
                </span>
              </button>
            </h5>
          </div>

          <div
            id="widgetcollapseOne"
            class="collapse show"
            aria-labelledby="widgetOne"
            data-parent="#accordionFooter"
          >
            <!-- List -->
            <ul
              class="list-unstyled text-gray-800 font-size-sm-alone mb-6 mb-md-8 mb-lg-0"
            >
              <li class="mb-3">
                <a href="{% url 'contact_us' %}" class="text-reset">
                  İletişim
                </a>
              </li>
              <li class="mb-3">
                <a href="{% url 'about_us' %}" class="text-reset">
                  Hakkımızda
                </a>
              </li>
              <li class="mb-3">
                <a href="{% url 'our_team' %}" class="text-reset"> Kadromuz </a>
              </li>
              <li class="mb-3">
                <a href="{% url 'single_course' %}" class="text-reset">
                  Kurslar
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-12 col-md-4 col-lg-2">
        <div class="mb-5 mb-xl-0 footer-accordion">
          <!-- Heading -->
          <div id="widgetTwo">
            <h5 class="mb-5">
              <button
                class="text-dark fw-medium footer-accordion-toggle d-flex align-items-center"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#widgetcollapseTwo"
                aria-expanded="false"
                aria-controls="widgetcollapseTwo"
              >
                Kategoriler
                <span class="ms-auto text-dark">
                  <!-- Icon -->
                  <svg
                    width="15"
                    height="2"
                    viewBox="0 0 15 2"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <rect width="15" height="2" fill="currentColor" />
                  </svg>

                  <svg
                    width="15"
                    height="16"
                    viewBox="0 0 15 16"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M0 7H15V9H0V7Z" fill="currentColor" />
                    <path
                      d="M6 16L6 8.74228e-08L8 0L8 16H6Z"
                      fill="currentColor"
                    />
                  </svg>
                </span>
              </button>
            </h5>
          </div>

          <div
            id="widgetcollapseTwo"
            class="collapse"
            aria-labelledby="widgetTwo"
            data-parent="#accordionFooter"
          >
            <!-- List -->
            <ul
              class="list-unstyled text-gray-800 font-size-sm-alone mb-6 mb-md-8 mb-lg-0 text-center"
            >
              {% for cat in category %}
              <li class="mb-3">
                <div class="d-flex align-items-center">
                  <!-- Icon -->
                  <div style="margin-right: 10px">
                    <i class="{{cat.icon}}"></i>
                  </div>
                  <div>{{cat.name}}</div>
                </div>
              </li>
              {% comment %} {% for i in cat.course_set.all %}
              <a class="dropdown-item" href="{{i.get_absolute_url}}">
                {{i.title}}
              </a>
              {% endfor %} {% endcomment %} {% endfor %}
            </ul>
          </div>
        </div>
      </div>

      <div class="col-12 col-md-4 offset-md-4 col-lg-2 offset-lg-0">
        <div class="mb-5 mb-xl-0 footer-accordion">
          <!-- Heading -->
          <div id="widgetThree">
            <h5 class="mb-5">
              <button
                class="text-dark fw-medium footer-accordion-toggle d-flex align-items-center"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#widgetcollapseThree"
                aria-expanded="false"
                aria-controls="widgetcollapseThree"
              >
                Kurslar
                <span class="ms-auto text-dark">
                  <!-- Icon -->
                  <svg
                    width="15"
                    height="2"
                    viewBox="0 0 15 2"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <rect width="15" height="2" fill="currentColor" />
                  </svg>

                  <svg
                    width="15"
                    height="16"
                    viewBox="0 0 15 16"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M0 7H15V9H0V7Z" fill="currentColor" />
                    <path
                      d="M6 16L6 8.74228e-08L8 0L8 16H6Z"
                      fill="currentColor"
                    />
                  </svg>
                </span>
              </button>
            </h5>
          </div>

          <div
            id="widgetcollapseThree"
            class="collapse"
            aria-labelledby="widgetThree"
            data-parent="#accordionFooter"
          >
            <!-- List -->
            {% for cat in category %}
            <ul class="list-unstyled text-gray-800 font-size-sm-alone mb-0">
              {% comment %} {% for i in cat.course_set.all %}
              <a class="dropdown-item" href="{{i.get_absolute_url}}">
                {{i.title}}
              </a>
              {% endfor %} {% endcomment %}
              <li class="mb-3">
                {% for i in cat.course_set.all %}
                <a class="dropdown-item" href="{{i.get_absolute_url}}">
                  {{i.title}}
                </a>
                {% endfor %}
              </li>
              {% comment %}
              <li class="mb-3">
                <a href="lesson-single-v2.html" class="text-reset"> ddd </a>
              </li>
              <li class="mb-3">
                <a href="lesson-single-v1.html" class="text-reset"> xxxx </a>
              </li>
              {% endcomment %}
            </ul>
            {% endfor %}
          </div>
        </div>
      </div>

      <div class="col-12 my-md-5">
        <div
          class="pb-5 pt-6 py-md-4 text-center text-xl-start d-flex flex-column d-md-block d-xl-flex flex-xl-row align-items-center"
        >
          <p
            class="text-gray-800 font-size-sm-alone d-block mb-0 mb-md-2 mb-xl-0 order-1 order-md-0 px-9 px-md-0"
          >
            Copyright © 2023 CourseMaster.
          </p>
        </div>
      </div>
    </div>
    <!-- / .row -->
  </div>
  <!-- / .container -->
</footer>

CourseMasterApp/templates/components/modals.html
{% load static %}

<!-- MODALS
    ================================================== -->
<!-- Modal Sidebar account -->
<div class="modal fade" id="modalExample" tabindex="-1" role="dialog" aria-labelledby="modalExampleTitle"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <!-- Close -->
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>

        <!-- Heading -->
        <h2 class="fw-bold text-center mb-1" id="modalExampleTitle">
          Schedule a demo with us
        </h2>

        <!-- Text -->
        <p class="font-size-lg text-center text-muted mb-6 mb-md-8">
          We can help you solve company communication.
        </p>

        <!-- Form -->
        <form>
          <div class="row">
            <div class="col-12 col-md-6">
              <!-- First name -->
              <div class="form-label-group">
                <input type="text" class="form-control form-control-flush" id="registrationFirstNameModal"
                  placeholder="First name" />
                <label for="registrationFirstNameModal">First name</label>
              </div>
            </div>
            <div class="col-12 col-md-6">
              <!-- Last name -->
              <div class="form-label-group">
                <input type="text" class="form-control form-control-flush" id="registrationLastNameModal"
                  placeholder="Last name" />
                <label for="registrationLastNameModal">Last name</label>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12 col-md-6">
              <!-- Email -->
              <div class="form-label-group">
                <input type="email" class="form-control form-control-flush" id="registrationEmailModal"
                  placeholder="Email" />
                <label for="registrationEmailModal">Email</label>
              </div>
            </div>
            <div class="col-12 col-md-6">
              <!-- Password -->
              <div class="form-label-group">
                <input type="password" class="form-control form-control-flush" id="registrationPasswordModal"
                  placeholder="Password" />
                <label for="registrationPasswordModal">Password</label>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <!-- Submit -->
              <button class="btn btn-block btn-primary mt-3 lift">
                Request a demo
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal modal-sidebar left fade-left fade" id="accountModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Signin -->
      <div class="collapse show" id="collapseSignin" data-bs-parent="#accountModal">
        <div class="modal-header">
          <h5 class="modal-title">CourseMaster Hesabınıza Giriş Yapın!</h5>
          <button type="button" class="close text-primary" data-bs-dismiss="modal" aria-label="Close">
            <!-- Icon -->
            <svg width="16" height="17" viewBox="0 0 16 17" xmlns="http://www.w3.org/2000/svg">
              <path d="M0.142135 2.00015L1.55635 0.585938L15.6985 14.7281L14.2843 16.1423L0.142135 2.00015Z"
                fill="currentColor"></path>
              <path d="M14.1421 1.0001L15.5563 2.41431L1.41421 16.5564L0 15.1422L14.1421 1.0001Z" fill="currentColor">
              </path>
            </svg>
          </button>
        </div>

        <div class="modal-body">
          <!-- Form Signin -->
          <form class="mb-5" method="post" action="{% url 'doLogin' %}">
            {% csrf_token %}
            <!-- Email -->
            <div class="form-group mb-5">
              <label for="modalSigninEmail"> Eposta </label>
              <input type="email" class="form-control" id="modalSigninEmail" placeholder="info@gmail.com"
                name="email" />
            </div>

            <!-- Password -->
            <div class="form-group mb-5">
              <label for="modalSigninPassword"> Şifre </label>
              <input type="password" class="form-control" id="modalSigninPassword" placeholder="**********"
                name="password" />
            </div>

            <div class="d-flex align-items-center mb-5 font-size-sm">
              <div class="form-check">
                <input class="form-check-input text-gray-800" type="checkbox" id="autoSizingCheck" />
                <label class="form-check-label text-gray-800" for="autoSizingCheck">
                  Beni Hatırla
                </label>
              </div>

              <div class="ms-auto">
                <a class="text-gray-800" data-bs-toggle="collapse" href="#collapseForgotPassword" role="button"
                  aria-expanded="false" aria-controls="collapseForgotPassword">Parolanızı mı unuttunuz?</a>
              </div>
            </div>

            <!-- Submit -->
            <button class="btn btn-block btn-primary" type="submit">
              GİRİŞ YAP
            </button>
          </form>

          <!-- Text -->
          <p class="mb-0 font-size-sm text-center">
            Hesabınız yok mu?
            <a class="text-underline" data-bs-toggle="collapse" href="#collapseSignup" role="button"
              aria-expanded="false" aria-controls="collapseSignup">Kayıt Ol</a>
          </p>
        </div>
      </div>

      <!-- Signup -->
      <div class="collapse" id="collapseSignup" data-bs-parent="#accountModal">
        <div class="modal-header">
          <h5 class="modal-title">Kaydolun ve Öğrenmeye Başlayın!</h5>
          <button type="button" class="close text-primary" data-bs-dismiss="modal" aria-label="Close">
            <!-- Icon -->
            <svg width="16" height="17" viewBox="0 0 16 17" xmlns="http://www.w3.org/2000/svg">
              <path d="M0.142135 2.00015L1.55635 0.585938L15.6985 14.7281L14.2843 16.1423L0.142135 2.00015Z"
                fill="currentColor"></path>
              <path d="M14.1421 1.0001L15.5563 2.41431L1.41421 16.5564L0 15.1422L14.1421 1.0001Z" fill="currentColor">
              </path>
            </svg>
          </button>
        </div>

        <div class="modal-body">
          <!-- Form Signup -->
          <form class="mb-5" method="post" action="{% url 'register' %}">
            {% csrf_token %}
            <!-- Username -->
            <div class="form-group mb-5">
              <label for="modalSignupUsername"> Kullanıcı Adı </label>
              <input type="text" class="form-control" id="modalSignupUsername" placeholder="info" name="username" />
            </div>

            <!-- Email -->
            <div class="form-group mb-5">
              <label for="modalSignupEmail"> Eposta </label>
              <input type="email" class="form-control" id="modalSignupEmail" placeholder="info@gmail.com"
                name="email" />
            </div>

            <!-- Password -->
            <div class="form-group mb-5">
              <label for="modalSignupPassword"> Şifre </label>
              <input type="password" class="form-control" id="modalSignupPassword" placeholder="**********"
                name="password" />
            </div>

            <!-- Submit -->
            <button class="btn btn-block btn-primary" type="submit">
              KAYIT OL
            </button>
          </form>

          <!-- Text -->
          <p class="mb-0 font-size-sm text-center">
            Zaten hesabınız var mı?
            <a class="text-underline" data-bs-toggle="collapse" href="#collapseSignin" role="button"
              aria-expanded="true" aria-controls="collapseSignin">Giriş Yap</a>
          </p>
        </div>
      </div>

      <!-- Forgot Password -->
      <div class="collapse" id="collapseForgotPassword" data-bs-parent="#accountModal">
        <div class="modal-header">
          <h5 class="modal-title">Şifre kurtarma!</h5>
          <button type="button" class="close text-primary" data-bs-dismiss="modal" aria-label="Close">
            <!-- Icon -->
            <svg width="16" height="17" viewBox="0 0 16 17" xmlns="http://www.w3.org/2000/svg">
              <path d="M0.142135 2.00015L1.55635 0.585938L15.6985 14.7281L14.2843 16.1423L0.142135 2.00015Z"
                fill="currentColor"></path>
              <path d="M14.1421 1.0001L15.5563 2.41431L1.41421 16.5564L0 15.1422L14.1421 1.0001Z" fill="currentColor">
              </path>
            </svg>
          </button>
        </div>

        <div class="modal-body">
          <!-- Form Recover Password -->
          <form class="mb-5">
            <!-- Email -->
            <div class="form-group">
              <label for="modalForgotpasswordEmail"> Eposta </label>
              <input type="email" class="form-control" id="modalForgotpasswordEmail" placeholder="info@gmail.com" />
            </div>

            <!-- Submit -->
            <button class="btn btn-block btn-primary" type="submit">
              ŞİFRE KURTARMA
            </button>
          </form>

          <!-- Text -->
          <p class="mb-0 font-size-sm text-center">
            Şifrenizi hatırlıyor musunuz?
            <a class="text-underline" data-bs-toggle="collapse" href="#collapseSignin" role="button"
              aria-expanded="false" aria-controls="collapseSignin">Giriş Yap</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

CourseMasterApp/templates/components/msg.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="close" data-dissmiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% elif message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="close" data-dissmiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="close" data-dissmiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}